AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Description: Name of the Environment with which the infrastructure is created

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      #The Family name will be used along with ECS_CLUSTER_NAME to prepare the stack name. It should be of Format abb-cdd-sd
      Family: Mongo
      ContainerDefinitions:
      - Name: mongo
        Cpu: '256'
        Essential: 'true'
        Image: mongo
        Memory: '512'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: CloudwatchLogsGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: mongo
        PortMappings:
        - ContainerPort: 27017
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Security Group
      VpcId:
        Fn::ImportValue:
           Fn::Sub:  "${EnvironmentName}-VPC"
      SecurityGroupIngress:
        # Only allow inbound access to ECS from the same VPC
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "ECS-Mongo-${AWS::StackName}"
      RetentionInDays: 14
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${EnvironmentName}-Mongo'
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Subnets:
        - Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-PublicSubnet1"
        - Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-PublicSubnet2"
      SecurityGroups:
      - Ref: ECSSecurityGroup
      - Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-ECSHostSecurityGroup"
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ECSServiceRole
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ECSTG
      LoadBalancerArn:
        Ref: ALB
      Port: '80'
      Protocol: HTTP
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: ECSTG
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn:
        Ref: ALBListener
      Priority: 1
  ECSTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ALB
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub '${EnvironmentName}-Mongo'
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
           Fn::Sub: "${EnvironmentName}-VPC"
  ECSServicePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ecs-service"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ['*']
            Resource: '*'
      Roles:
      - Ref: ECSServiceRole
  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSServicePolicy
      - ALB
      - ALBListener
    Properties:
      Cluster:
        Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-ECSCluster"
      DesiredCount: '2'
      TaskDefinition:
        Ref: TaskDefinition
      LoadBalancers:
      - ContainerName: mongo
        ContainerPort: '27017'
        TargetGroupArn:
          Ref: ECSTG
      Role:
        Ref: ECSServiceRole
Outputs:
  ecsservice:
    Value:
      Ref: Service
  AppALBDNS:
    Value:
      "Fn::GetAtt": [ ALB, DNSName ]
